version: '3.8'

services:
  nats:
    image: nats:2.10.7-alpine
    container_name: nats-server
    ports:
      - "4222:4222"  # NATS client port
      - "8222:8222"  # HTTP monitoring port
      - "6222:6222"  # Routing port
    command:
      - "--http_port"
      - "8222"
      - "--name"
      - "nats-server"
      - "--log"
      - "/dev/stdout"
    volumes:
      - nats_data:/data
    networks:
      - nats-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/varz"]
      interval: 30s
      timeout: 10s
      retries: 3

  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=oracle123
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata
      - oracle_startup:/opt/oracle/scripts/startup
      - oracle_setup:/opt/oracle/scripts/setup
    networks:
      - nats-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sqlplus", "-S", "sys/oracle123@localhost:1521/XE", "as", "sysdba", "<<<", "SELECT 1 FROM DUAL;"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  nats_data:
  oracle_data:
  oracle_startup:
  oracle_setup:

networks:
  nats-network:
    driver: bridge