version: '3.8'

services:
  nats:
    image: nats:2.10.7-alpine
    container_name: nats-server
    ports:
      - "14222:4222"  # NATS client port
      - "18222:8222"  # HTTP monitoring port
    command:
      - "--http_port"
      - "8222"
      - "--name"
      - "nats-server"
      - "--log"
      - "/dev/stdout"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/varz"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nats-network

  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=oracle123
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - nats-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "sqlplus", "-S", "sys/oracle123@localhost:1521/XE", "as", "sysdba", "<<<", "SELECT 1 FROM DUAL;"]
      interval: 30s
      timeout: 10s
      retries: 5

  nats-client:
    image: nats-client:latest
    container_name: nats-client-app
    ports:
      - "8080:8080"
    environment:
      - NATS_URL=nats://nats:4222
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_CLOUD_VAULT_ENABLED=false
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521:xe
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=oracle123
    depends_on:
      nats:
        condition: service_healthy
      oracle-db:
        condition: service_healthy
    networks:
      - nats-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  oracle_data:

networks:
  nats-network:
    driver: bridge