apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
  labels:
    app: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
      - name: oracle-xe
        image: container-registry.oracle.com/database/express:21.3.0-xe
        ports:
        - containerPort: 1521
          name: oracle
        - containerPort: 5500
          name: apex
        env:
        - name: ORACLE_PWD
          value: "oracle123"
        - name: ORACLE_CHARACTERSET
          value: "AL32UTF8"
        volumeMounts:
        - name: oracle-data
          mountPath: /opt/oracle/oradata
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "echo 'SELECT 1 FROM DUAL;' | sqlplus -S sys/oracle123@localhost:1521/XE as sysdba"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "echo 'SELECT 1 FROM DUAL;' | sqlplus -S sys/oracle123@localhost:1521/XE as sysdba"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: oracle-data
        persistentVolumeClaim:
          claimName: oracle-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-db
  labels:
    app: oracle-db
spec:
  ports:
  - port: 1521
    targetPort: 1521
    name: oracle
  - port: 5500
    targetPort: 5500
    name: apex
  selector:
    app: oracle-db
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-db-external
  labels:
    app: oracle-db
spec:
  ports:
  - port: 1521
    targetPort: 1521
    nodePort: 31521
    name: oracle
  - port: 5500
    targetPort: 5500
    nodePort: 31500
    name: apex
  selector:
    app: oracle-db
  type: NodePort