# Complete Kubernetes deployment for NATS Client application
# This file combines all services for easy deployment

# Oracle Database PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# NATS Server Deployment with JetStream
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-server
  labels:
    app: nats-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-server
  template:
    metadata:
      labels:
        app: nats-server
    spec:
      containers:
      - name: nats
        image: nats:2.10.7-alpine
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 8222
          name: monitoring
        args:
        - "--http_port"
        - "8222"
        - "--name"
        - "nats-server"
        - "--log"
        - "/dev/stdout"
        - "--jetstream"
        - "--store_dir=/nats/jetstream"
        volumeMounts:
        - name: jetstream-storage
          mountPath: /nats/jetstream
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /varz
            port: 8222
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /varz
            port: 8222
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: jetstream-storage
        emptyDir: {}
---
# NATS Server Service
apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app: nats-server
spec:
  ports:
  - port: 4222
    targetPort: 4222
    name: client
  - port: 8222
    targetPort: 8222
    name: monitoring
  selector:
    app: nats-server
  type: ClusterIP
---
# Oracle Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
  labels:
    app: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
      - name: oracle-xe
        image: container-registry.oracle.com/database/express:21.3.0-xe
        ports:
        - containerPort: 1521
          name: oracle
        - containerPort: 5500
          name: apex
        env:
        - name: ORACLE_PWD
          value: "oracle123"
        - name: ORACLE_CHARACTERSET
          value: "AL32UTF8"
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: oracle-data
          mountPath: /opt/oracle/oradata
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "echo 'SELECT 1 FROM DUAL;' | sqlplus -S sys/oracle123@localhost:1521/XE as sysdba"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "echo 'SELECT 1 FROM DUAL;' | sqlplus -S sys/oracle123@localhost:1521/XE as sysdba"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: oracle-data
        persistentVolumeClaim:
          claimName: oracle-data-pvc
---
# Oracle Database Service
apiVersion: v1
kind: Service
metadata:
  name: oracle-db
  labels:
    app: oracle-db
spec:
  ports:
  - port: 1521
    targetPort: 1521
    name: oracle
  - port: 5500
    targetPort: 5500
    name: apex
  selector:
    app: oracle-db
  type: ClusterIP
---
# NATS Client Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-client-app
  labels:
    app: nats-client-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-client-app
  template:
    metadata:
      labels:
        app: nats-client-app
    spec:
      containers:
      - name: nats-client
        image: nats-client:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NATS_URL
          value: "nats://nats:4222"
        - name: SPRING_PROFILES_ACTIVE
          value: "local"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:oracle:thin:@oracle-db:1521:xe"
        - name: SPRING_DATASOURCE_USERNAME
          value: "system"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "oracle123"
        - name: NATS_JETSTREAM_ENABLED
          value: "true"
        - name: NATS_JETSTREAM_STREAM_NAME
          value: "K8S_STREAM"
        - name: NATS_JETSTREAM_STORAGE
          value: "MEMORY"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        imagePullPolicy: Never
      initContainers:
      - name: wait-for-nats
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z nats 4222; do echo waiting for nats; sleep 2; done;']
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"
      - name: wait-for-oracle
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z oracle-db 1521; do echo waiting for oracle; sleep 2; done;']
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"
---
# NATS Client Application Service (External Access)
apiVersion: v1
kind: Service
metadata:
  name: nats-client-external
  labels:
    app: nats-client-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http
  selector:
    app: nats-client-app
  type: NodePort
---
# NATS External Service (for monitoring)
apiVersion: v1
kind: Service
metadata:
  name: nats-external
  labels:
    app: nats-server
spec:
  ports:
  - port: 4222
    targetPort: 4222
    nodePort: 30422
    name: client
  - port: 8222
    targetPort: 8222
    nodePort: 30822
    name: monitoring
  selector:
    app: nats-server
  type: NodePort