apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-server
  labels:
    app: nats-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-server
  template:
    metadata:
      labels:
        app: nats-server
    spec:
      containers:
      - name: nats
        image: nats:2.10.7-alpine
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 8222
          name: monitoring
        args:
        - "--http_port"
        - "8222"
        - "--name"
        - "nats-server"
        - "--log"
        - "/dev/stdout"
        livenessProbe:
          httpGet:
            path: /varz
            port: 8222
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /varz
            port: 8222
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app: nats-server
spec:
  ports:
  - port: 4222
    targetPort: 4222
    name: client
  - port: 8222
    targetPort: 8222
    name: monitoring
  selector:
    app: nats-server
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nats-external
  labels:
    app: nats-server
spec:
  ports:
  - port: 4222
    targetPort: 4222
    nodePort: 30422
    name: client
  - port: 8222
    targetPort: 8222
    nodePort: 30822
    name: monitoring
  selector:
    app: nats-server
  type: NodePort