spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ${DB_USERNAME:your_username}
    password: ${DB_PASSWORD:your_password}
    driver-class-name: oracle.jdbc.OracleDriver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: TRACE
    show-sql: true

  application:
    name: nats-client

nats:
  url: ${NATS_URL:nats://localhost:4222}
  connection-name: ${NATS_CONNECTION_NAME:nats-client-service}
  # Authentication options (choose one)
  username: ${NATS_USERNAME:}
  password: ${NATS_PASSWORD:}
  token: ${NATS_TOKEN:}
  credentials: ${NATS_CREDENTIALS_FILE:}
  
  connection:
    timeout: ${NATS_CONNECTION_TIMEOUT:10000}
    ping-interval: ${NATS_PING_INTERVAL:120000}
    request-cleanup-interval: ${NATS_REQUEST_CLEANUP_INTERVAL:300000}
    no-echo: ${NATS_NO_ECHO:false}
    max-control-line: ${NATS_MAX_CONTROL_LINE:1024}
    reconnect:
      wait: ${NATS_RECONNECT_WAIT:2000}
      max-attempts: ${NATS_MAX_RECONNECTS:-1}
  request:
    timeout: ${NATS_REQUEST_TIMEOUT:30000}
    
  # TLS configuration
  tls:
    enabled: ${NATS_TLS_ENABLED:false}
    keystore: ${NATS_TLS_KEYSTORE:}
    keystorePassword: ${NATS_TLS_KEYSTORE_PASSWORD:}
    truststore: ${NATS_TLS_TRUSTSTORE:}
    truststorePassword: ${NATS_TLS_TRUSTSTORE_PASSWORD:}
  
  # Logging configuration
  logging:
    enable-connection-events: ${NATS_LOG_CONNECTION_EVENTS:true}
    enable-error-logging: ${NATS_LOG_ERRORS:true}
    enable-slow-consumer-warning: ${NATS_LOG_SLOW_CONSUMER:true}

logging:
  level:
    com.example.natsclient: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

---
# Kubernetes Profile
spring:
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST:oracle-db}:${DB_PORT:1521}:${DB_SID:xe}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# Vault Agent 和 K8s Secret 掛載路徑
nats:
  url: ${NATS_URL:nats://nats-server:4222}
  connection-name: ${NATS_CONNECTION_NAME:nats-client-k8s}
  credentials:
    vault-path: /vault/secrets
    k8s-secret-path: /etc/secrets/nats

---
# Local Development Profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: oracle123

nats:
  url: nats://localhost:14222
  connection-name: ${NATS_CONNECTION_NAME:nats-client-local}
  # 本地開發不需要認證