spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: TRACE
    show-sql: true

  application:
    name: nats-client

nats:
  url: ${NATS_URL:nats://localhost:4222}
  connection-name: ${NATS_CONNECTION_NAME:nats-client-service}
  # Authentication options (choose one) - 敏感資料透過環境變數從 Vault 取得
  username: ${NATS_USERNAME}
  password: ${NATS_PASSWORD}
  token: ${NATS_TOKEN}
  credentials: ${NATS_CREDENTIALS_FILE}
  
  connection:
    timeout: ${NATS_CONNECTION_TIMEOUT:10000}
    ping-interval: ${NATS_PING_INTERVAL:120000}
    request-cleanup-interval: ${NATS_REQUEST_CLEANUP_INTERVAL:300000}
    no-echo: ${NATS_NO_ECHO:false}
    max-control-line: ${NATS_MAX_CONTROL_LINE:1024}
    reconnect:
      wait: ${NATS_RECONNECT_WAIT:2000}
      max-attempts: ${NATS_MAX_RECONNECTS:-1}
  request:
    timeout: ${NATS_REQUEST_TIMEOUT:30000}
    
  # TLS configuration - 敏感資料透過環境變數從 Vault 取得
  tls:
    enabled: ${NATS_TLS_ENABLED:false}
    keystore: ${NATS_TLS_KEYSTORE}
    keystorePassword: ${NATS_TLS_KEYSTORE_PASSWORD}
    truststore: ${NATS_TLS_TRUSTSTORE}
    truststorePassword: ${NATS_TLS_TRUSTSTORE_PASSWORD}
  
  # Logging configuration
  logging:
    enable-connection-events: ${NATS_LOG_CONNECTION_EVENTS:true}
    enable-error-logging: ${NATS_LOG_ERRORS:true}
    enable-slow-consumer-warning: ${NATS_LOG_SLOW_CONSUMER:true}

  # JetStream configuration
  jet-stream:
    enabled: ${NATS_JETSTREAM_ENABLED:true}
    domain: ${NATS_JETSTREAM_DOMAIN:}
    prefix: ${NATS_JETSTREAM_PREFIX:$JS.API}
    default-timeout: ${NATS_JETSTREAM_DEFAULT_TIMEOUT:5000}
    
    publish-ack:
      timeout: ${NATS_JETSTREAM_PUBLISH_TIMEOUT:5000}
      wait-for-ack: ${NATS_JETSTREAM_WAIT_FOR_ACK:true}
    
    subscribe:
      ack-timeout: ${NATS_JETSTREAM_ACK_TIMEOUT:30000}
      max-deliver: ${NATS_JETSTREAM_MAX_DELIVER:3}
      deliver-policy: ${NATS_JETSTREAM_DELIVER_POLICY:NEW}
    
    stream:
      default-name: ${NATS_JETSTREAM_STREAM_NAME:DEFAULT_STREAM}
      subjects: 
        - "jetstream.>"
        - "js.>"
        - "stream.>"
      storage: ${NATS_JETSTREAM_STORAGE:MEMORY}
      max-age: ${NATS_JETSTREAM_MAX_AGE:86400000} # 24 hours in milliseconds
      max-msgs: ${NATS_JETSTREAM_MAX_MSGS:100000}
      replicate: ${NATS_JETSTREAM_REPLICATE:false}
      replicas: ${NATS_JETSTREAM_REPLICAS:1}

# OpenAPI/Swagger Configuration - 最簡配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# Management Endpoints for OpenAPI
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# Application Information for OpenAPI
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    java-version: '@java.version@'

logging:
  level:
    com.example.natsclient: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

---
# Kubernetes Profile
spring:
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST:oracle-db}:${DB_PORT:1521}:${DB_SID:xe}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

nats:
  url: ${NATS_URL:nats://nats-server:4222}
  connection-name: ${NATS_CONNECTION_NAME:nats-client-k8s}
  # 敏感資料透過環境變數從 Vault 取得
  username: ${NATS_USERNAME}
  password: ${NATS_PASSWORD}
  token: ${NATS_TOKEN}
  credentials: ${NATS_CREDENTIALS_FILE}

---
# Local Development Profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: oracle123

nats:
  url: nats://localhost:14222
  connection-name: ${NATS_CONNECTION_NAME:nats-client-local}
  # 本地開發不需要認證