-- NATS Request Tracking Table
CREATE TABLE NATS_REQUEST_LOG (
    ID NUMBER(19) PRIMARY KEY,
    REQUEST_ID VARCHAR2(255) NOT NULL UNIQUE,
    SUBJECT VARCHAR2(255) NOT NULL,
    REQUEST_PAYLOAD CLOB,
    REQUEST_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RESPONSE_PAYLOAD CLOB,
    RESPONSE_TIMESTAMP TIMESTAMP,
    STATUS VARCHAR2(50) DEFAULT 'PENDING',
    ERROR_MESSAGE CLOB,
    RETRY_COUNT NUMBER(3) DEFAULT 0,
    TIMEOUT_DURATION NUMBER(10),
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create sequence for ID generation
CREATE SEQUENCE NATS_REQUEST_LOG_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create trigger for auto-incrementing ID
CREATE OR REPLACE TRIGGER NATS_REQUEST_LOG_TRG
    BEFORE INSERT ON NATS_REQUEST_LOG
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT NATS_REQUEST_LOG_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.CREATED_DATE := CURRENT_TIMESTAMP;
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;

-- Create trigger for updating UPDATED_DATE on update
CREATE OR REPLACE TRIGGER NATS_REQUEST_LOG_UPD_TRG
    BEFORE UPDATE ON NATS_REQUEST_LOG
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;

-- Create indexes for better performance
CREATE INDEX IDX_NATS_REQ_REQUEST_ID ON NATS_REQUEST_LOG(REQUEST_ID);
CREATE INDEX IDX_NATS_REQ_STATUS ON NATS_REQUEST_LOG(STATUS);
CREATE INDEX IDX_NATS_REQ_TIMESTAMP ON NATS_REQUEST_LOG(REQUEST_TIMESTAMP);

-- Comments for table and columns
COMMENT ON TABLE NATS_REQUEST_LOG IS 'Table to track NATS requests and responses';
COMMENT ON COLUMN NATS_REQUEST_LOG.REQUEST_ID IS 'Unique identifier for the request';
COMMENT ON COLUMN NATS_REQUEST_LOG.SUBJECT IS 'NATS subject/topic';
COMMENT ON COLUMN NATS_REQUEST_LOG.STATUS IS 'Request status: PENDING, SUCCESS, FAILED, TIMEOUT, ERROR';
COMMENT ON COLUMN NATS_REQUEST_LOG.RETRY_COUNT IS 'Number of retry attempts made';
COMMENT ON COLUMN NATS_REQUEST_LOG.TIMEOUT_DURATION IS 'Timeout duration in milliseconds';
