apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-client
  namespace: default
  labels:
    app: nats-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nats-client
  template:
    metadata:
      labels:
        app: nats-client
      annotations:
        # Vault Agent 注入配置
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "nats-client"
        vault.hashicorp.com/agent-inject-secret-nats.json: "secret/data/nats"
        vault.hashicorp.com/agent-inject-template-nats.json: |
          {{- with secret "secret/data/nats" -}}
          {
            "data": {
              "url": "{{ .Data.data.url }}",
              "username": "{{ .Data.data.username }}",
              "password": "{{ .Data.data.password }}",
              "token": "{{ .Data.data.token }}",
              "credentials_file": "{{ .Data.data.credentials_file }}"
            }
          }
          {{- end -}}
    spec:
      serviceAccountName: nats-client
      containers:
      - name: nats-client
        image: nats-client:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        # 環境變數作為fallback
        - name: NATS_URL
          valueFrom:
            secretKeyRef:
              name: nats-credentials
              key: url
              optional: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        # K8s Secret掛載 (如果不使用Vault Agent)
        - name: nats-secret
          mountPath: /etc/secrets/nats
          readOnly: true
        # Vault Agent會將secrets寫到這裡
        - name: vault-secrets
          mountPath: /vault/secrets
          readOnly: true
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nats-secret
        secret:
          secretName: nats-credentials
          optional: true
      - name: vault-secrets
        emptyDir: {}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-client
  namespace: default
  annotations:
    # 綁定Vault role
    vault.hashicorp.com/role: "nats-client"

---
apiVersion: v1
kind: Secret
metadata:
  name: nats-credentials
  namespace: default
type: Opaque
data:
  # Base64 encoded values (範例)
  url: bmF0czovL25hdHMtc2VydmVyOjQyMjI=  # nats://nats-server:4222
  username: bmF0c191c2Vy  # nats_user
  password: bmF0c19wYXNzd29yZA==  # nats_password

---
apiVersion: v1
kind: Service
metadata:
  name: nats-client-service
  namespace: default
spec:
  selector:
    app: nats-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP