-- H2 Database Schema for Testing
-- NATS Request Tracking Table
CREATE TABLE NATS_REQUEST_LOG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    REQUEST_ID VARCHAR(255) NOT NULL UNIQUE,
    SUBJECT VARCHAR(255) NOT NULL,
    REQUEST_PAYLOAD CLOB,
    REQUEST_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RESPONSE_PAYLOAD CLOB,
    RESPONSE_TIMESTAMP TIMESTAMP,
    STATUS VARCHAR(50) DEFAULT 'PENDING',
    ERROR_MESSAGE CLOB,
    RETRY_COUNT INT DEFAULT 0,
    TIMEOUT_DURATION BIGINT,
    CORRELATION_ID VARCHAR(255),
    CREATED_BY VARCHAR(100),
    UPDATED_BY VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX IDX_NATS_REQ_REQUEST_ID ON NATS_REQUEST_LOG(REQUEST_ID);
CREATE INDEX IDX_NATS_REQ_STATUS ON NATS_REQUEST_LOG(STATUS);
CREATE INDEX IDX_NATS_REQ_TIMESTAMP ON NATS_REQUEST_LOG(REQUEST_TIMESTAMP);
CREATE INDEX IDX_NATS_REQ_CORR_ID ON NATS_REQUEST_LOG(CORRELATION_ID);